### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'plugin\\demotion\\G.pth'

### ISSUE THREAD

**Issue by ZhaoLizz** [MashiMaroLjc/elegance#2]
```
C:\Users\Administrator\PycharmProjects\elegance>python elegance.py demotion test.jpg
[INFO]USING PLUGIN: demotion
Traceback (most recent call last):
  File "elegance.py", line 69, in <module>
    main(args)
  File "elegance.py", line 52, in main
    generate, preprocess, postprocess = util.load_plugin(args.plugin, params)
  File "C:\Users\Administrator\PycharmProjects\elegance\util.py", line 64, in load_plugin
    generator.load_state_dict(torch.load(weight_path, map_location=lambda storage, loc: storage))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'plugin\\demotion\\G.pth'
```
我把test.jpg放在项目的根目录,使用`python elegance.py demotion test.jpg`命令,但是得到了上述错误.希望作者能够提供帮助.谢谢!

**Comment by MashiMaroLjc** [comment]
请问你在release的目录下下载了相关的预训练模型了吗？

**Comment by ZhaoLizz** [comment]
sorry,我没有找到release下的预训练模型下载链接,请问在哪里呢

**Comment by zhaowei11594** [comment]
没有release目录哇
